# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Ping++支付' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Pingpp/Alipay'
pod 'Pingpp/UnionPay'
pod 'Pingpp/One'
  # Pods for Ping++支付

end
