# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift练习' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 3.0'
  # Pods for Swift练习

end
